import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/Header/Header";
import Footer from "./components/Footer/Footer";
import { Suspense } from "react";
import Loading from "./loading";

export const metadata: Metadata = {
  title: "Create Next App - Clemerson Costa",
  description: "Generated by create next app --typescript",
};

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
  return (    
    <html lang="pt">
      <body>
        <Header />
          <Suspense fallback={<Loading />}>
            {children}
          </Suspense>
        <Footer />
      </body>
    </html>
  );
}
