'use client'

// import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/Header/Header";
import Footer from "./components/Footer/Footer";
import { Suspense } from "react";
import Loading from "./loading";
import { ApolloProvider } from '@apollo/client';
import apolloClient from '../apollo/apolloClient';

// export const metadata: Metadata = {
//   title: "Create Next App - Clemerson Costa",
//   description: "Generated by create next app --typescript",
// };

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
  return (    
    <html lang="pt">
      <body>
        <Header />
          <ApolloProvider client={apolloClient}>
            <Suspense fallback={<Loading />}>
              {children}
            </Suspense>
          </ApolloProvider> 
        <Footer />
      </body>
    </html>
  );
}
